node {
	stage('Clone repository') {
		/* Let's make sure we have the repository cloned to our workspace */

		checkout scm
	}

	environment {
		DAILYTAG="""${sh(
			returnStdout: true,
			script: 'date +%Y%m%d'
		)}"""
	}

	def alpine

	stage('Print environment') {
		sh 'printenv'
	}

	stage('Build image') {
		alpine = docker.build("kleinf/alpine:${env.DAILYTAG}", "--force-rm", "./alpine")
	}

	stage('Test image') {
		/* Ideally, we would run a test framework against our image.
		* For this example, we're using a Volkswagen-type approach ;-) */

		alpine.inside {
			sh 'echo "Tests passed"'
		}
	}

	stage('Push image') {
		docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
			alpine.push("${env.DAILYTAG}")
		}
	}
}
